social/dwitterApp/urls.py
from django.urls import path
from . import views
app_name = "dwitterApp"

urlpatterns = [

    path("", views.dashboard, name="dashboard"),
    path('profile_list/', views.profile_list, name='profile_list'),
    path('profile/<int:pk>', views.profile, name='profile')
]

social/social/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('dwitterApp.urls')),
    
]

social/dwitterApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,
        blank=True
    )
    def __str__(self):
            return self.user.username
        
    # Create your models here.
# @receiver(post_save, sender=User)
# def create_profile(sender, instance, created, **kwargs):

#         if created:
#             user_profile = Profile(user=instance)
#             user_profile.save()
#             user_profile.follows.set([instance.profile.id])
#             user_profile.save()

      


# Create a Profile for each new user.

# post_save.connect(create_profile, sender=User)

class Dweet(models.Model):
    user = models.ForeignKey(User, related_name="dweets", on_delete=models.DO_NOTHING)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    # class Meta:
    #     ordering = ["-created_at"]

    def __str__(self) -> str:
        return self.body

social/dwitterApp/forms.py
from django import forms
from .models import Dweet
class DweetForm(forms.ModelForm):
    body = forms.CharField(
    required=True,
    widget=forms.widgets.Textarea(
    attrs={
        "placeholder": "Dweet something...",
        "class": "textarea is-success is-medium",
        }
    ),
    label="",
    )
    class Meta:
        model = Dweet
        exclude = ("user",)
        

social/dwitterApp/views.py
from django.shortcuts import render,redirect
from .models import Profile,Dweet
from .forms import DweetForm

# Create your views here.

def dashboard(request):
    form = DweetForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            dweet = form.save(commit=False)
            dweet.user = request.user
            dweet.save()
            return redirect('dwitterApp:dashboard')
    follow_dweets = Dweet.objects.filter(user__profile__in = request.user.profile.follows.all()).order_by('-created_at')
    return render(request, "dwitterApp/dashboard.html", {"form": form,"dweets":follow_dweets}) 

def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "dwitterApp/profile_list.html", {"profiles": profiles})

def profile(request, pk):
    if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()

    profile = Profile.objects.get(pk=pk)
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        
        current_user_profile.save()
    return render(request,'dwitterApp/profile.html',{"profile":profile})

social/dwitterApp/templates/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Include the Bulma CSS framework for styling -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
        <title>Dwitter</title>
    </head>

    <body>
        <section class="hero is-small is-success mb-4">
            <div class="hero-body">
                <h1 class="title is-1">Dwitter</h1>
                <p class="subtitle is-4">
                    Your tiny social network built with Django
                </p>
            </div>
        </section>
        <div class="container">
            <div class="columns">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </body>

</html>

social/dwitterApp/templates/dwitterApp/dashboard.html
<!-- dwitter/templates/dwitter/dashboard.html -->
{% extends 'base.html' %}
{% block content %}
<div class="column">
        {% for dweet in dweets %}
        <div class="box">
            {{ dweet.body }}
            <span class="is-small has-text-grey-light">
                ({{ dweet.created_at }} by {{ dweet.user.username }}
            </span>
        </div>
    {% endfor %}
</div>
<div class="column is-one-third">
    <a href="{% url 'dwitterApp:profile' request.user.profile.id %}" class="button is-dark is-outlined is-fullwidth is-medium mb-5"> My Profile</a>
    <a href="{% url 'dwitterApp:profile_list'%}" class="button is-success  is-outlined is-fullwidth is-medium mb-5"> All Profile</a>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button is-success is-fullwidth is-medium mt-5" type="submit">Dweet
        </button>
    </form>
</div>
{% endblock content %}

social/dwitterApp/templates/dwitterApp/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="column">
    <div class="block">
        <h1 class="title is-1">
            {{profile.user.username|upper}}'s Dweets
        </h1>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="buttons has-addons">
            {% if profile in user.profile.follows.all %}
            <button class="button is-success is-static">Follow</button>
            <button class="button is-danger" name="follow" value="unfollow">
                Unfollow
            </button>
            {% else %}
            <button class="button is-success" name="follow" value="follow">
                Follow
            </button>
            <button class="button is-danger is-static">Unfollow</button>
            {% endif %}
        </div>
    </form>
    <div class="content">
        {% for dweet in profile.user.dweets.all %}
        <div class="box">
            {{ dweet.body }}
            <span class="is-small has-text-grey-light">
                ({{ dweet.created_at }})
            </span>
        </div>
        {% endfor %}
    </div>
</div>
<div class="column is-one-third">
    <div class="block">
        <a href="{% url 'dwitterApp:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} follows:
        </h3>
        <div class="content">
            <ul>
                {% for following in profile.follows.all %}
                <li>
                    <a href="{% url 'dwitterApp:profile' following.id %}">
                        {{ following }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} is followed by:
        </h3>
        <div class="content">
            <ul>
                {% for follower in profile.followed_by.all %}
                <li>
                    <a href="{% url 'dwitterApp:profile' follower.id %}">
                        {{ follower }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock content %}

social/dwitterApp/templates/dwitterApp/profile_list.html
{% extends 'base.html' %}
{% block content %}
<div class="column">
    {% for profile in profiles %}
    <div class="block">
        <div class="card">
        <a href="{% url 'dwitterApp:profile' profile.id %}">
                <div class="card-content">
                    <div class="media">
                        <div class="media-left">
                            <figure class="image is-48x48">
                                <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                            </figure>
                        </div>
                        <div class="media-content">
                            <p class="title is-4">
                                {{ profile.user.username }}
                            </p>
                            <p class="subtitle is-6">
                                @{{ profile.user.username|lower }}
                            </p>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}